user www-data;
worker_processes auto;
pid /run/nginx/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /dev/stdout main;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 1g;
    client_body_timeout 300s;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        '' $scheme;
    }

    map $http_x_forwarded_host $forwarded_host {
        default $http_x_forwarded_host;
        '' $host;
    }

    map $http_x_forwarded_port $forwarded_port {
        default $http_x_forwarded_port;
        '' $server_port;
    }

    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html/public;
        index index.php;

        location /app {
            proxy_http_version 1.1;
            proxy_set_header Host $forwarded_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $forwarded_host;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            proxy_set_header X-Forwarded-Port $forwarded_port;
            proxy_pass http://127.0.0.1:8080;
        }

        location /apps {
            proxy_http_version 1.1;
            proxy_set_header Host $forwarded_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $forwarded_host;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            proxy_set_header X-Forwarded-Port $forwarded_port;
            proxy_pass http://127.0.0.1:8080;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include /etc/nginx/fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_PROXY "";
            fastcgi_param HTTP_X_FORWARDED_HOST $forwarded_host;
            fastcgi_param HTTP_X_FORWARDED_PROTO $forwarded_proto;
            fastcgi_param HTTP_X_FORWARDED_PORT $forwarded_port;
            fastcgi_read_timeout 300s;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
